### ISSUE TITLE
Gear tilted on the ground

### ISSUE THREAD

**Issue by ItzLincoln** [LincolnWorks-FlightGear/747-400#1]
https://cdn.discordapp.com/attachments/705421460696727592/705760662076260402/unknown.png

gear is tilted on the ground causing stickshaker+massive wingflex

**Comment by ItzLincoln** [comment]
Update:After further investigation the 747-FO model does not actively show this bug. We suspect a issue with code somewhere

**Comment by Marsdolphin** [comment]
After testing this is what I see: https://cdn.discordapp.com/attachments/705421460696727592/705775265636286514/Screen_Shot_2020-05-01_at_9.29.02_PM.png

**Comment by ItzLincoln** [comment]
That is however the FO model

**Comment by ItzLincoln** [comment]
Closing and opening a new issue. Wingflex is not caused by the tilted gear.
